(* ----------------------------------------------------------------- *)
(*  kiru DSL - EBNF Grammar                                         *)
(* ----------------------------------------------------------------- *)

(* ================================================================= *)
(*  PROGRAM                                                          *)
(* ================================================================= *)

program          = { statement } ;
statement        = import_decl | var_decl
                 | fn_decl | project_decl | run_decl ;

(* ================================================================= *)
(*  GLOBAL DECLARATIONS                                              *)
(* ================================================================= *)

import_decl      = "import" template ";" ;
var_decl         = "var" ident "=" template ";" ;

(* ================================================================= *)
(*  FUNCTION (always inside a project)                               *)
(* ================================================================= *)

fn_decl          = "fn" ident "{" { fn_stmt } "}" ";" ;
fn_stmt          = log_stmt | exec_stmt | cd_stmt
                 | var_decl | env_block | switch_stmt ;

log_stmt         = "log"  template ";" ;
exec_stmt        = "$(" template ")" ";" ;
cd_stmt          = "cd"   template ";" ;

(* -- env block ---------------------------------------------------- *)

env_block        = "env" "{" { env_pair } "}" "{" { fn_stmt } "}" ";" ;
env_pair         = ident "=" template ";" ;

(* -- switch block ------------------------------------------------- *)

switch_stmt      = "switch" template "{" { case_arm } "}" ";" ;
case_arm         = "case" case_pattern "{" { fn_stmt } "}" ";" ;
case_pattern     = template               (* literal match          *)
                 | "_" ;                  (* default / catch-all    *)

(* ================================================================= *)
(*  PROJECT - declares a scope for vars and functions                *)
(* ================================================================= *)

project_decl     = "pr" ident "{" { project_stmt } "}" ;
project_stmt     = var_decl | fn_decl ;

(* ================================================================= *)
(*  RUN BLOCK - orchestrates functions across projects               *)
(* ================================================================= *)

run_decl         = "run" ident "{" { chain } "}" ;
chain            = qualified_fn_ref { "=> qualified_fn_ref } ";" ;
qualified_fn_ref = ident "::" ident ;     (* project::function      *)

(* ================================================================= *)
(*  TEMPLATES / EXPRESSIONS                                         *)
(* ================================================================= *)

(* a template is (text), @(name) to use a variable, or $(command)   *)
(* to run one                                                       *)

template         = "(" { template_part } ")"
                 | "$(" { template_part } ")"
                 | "@(" { template_part } ")"
                 | ident ;

template_part    = lit_text
                 | "@(" ident ")"
                 | "$(" template ")" ;

lit_text         = ? any character except ")", "@(", "$( " ? ;

(* ================================================================= *)
(*  LEXICAL TOKENS                                                   *)
(* ================================================================= *)

ident            = ( letter | "_" ) { letter | digit | "_" } ;
letter           = "A" | "B" | ... | "Z" | "a" | "b" | ... | "z" ;
digit            = "0" | "1" | ... | "9" ;

(* Keywords (reserved, cannot be used as identifiers):               *)
(*   import var pr fn run log cd env switch case                     *)
(*                                                                   *)
(* Comments start with # and run to end of line.                     *)
(* Semicolons are mandatory in fn bodies and after var declarations. *)
(* ----------------------------------------------------------------- *)
