name: CI

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'main.kiru'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/ci.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'main.kiru'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rust:alpine
    steps:
      - name: Install Build Dependencies
        run: apk add --no-cache git

      - name: Install Rust Tools
        run: |
          rustup component add clippy rustfmt

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build
        run: cargo build

      - name: Checks
        run: |
          cargo clippy --all-targets -- -D warnings
          cargo test
          cargo fmt --check

      - name: Compile the pipeline
        run: ./target/debug/kc main.kiru
